import Head from "next/head";
import { Inter } from "next/font/google";
import {
  Box,
  Button,
  Center,
  Flex,
  Heading,
  Radio,
  RadioGroup,
  Stack,
  Text,
  useMediaQuery,
} from "@chakra-ui/react";
import { SetStateAction, useState } from "react";
import HowDoCard from "./components/howDoCard";

export default function Home() {
  const colorPallete = {
    schem: "",
    primary_blue: "#1b263b",
    secondary_blue: "#0077b6",
    white: "#fff",
    black: "#000",
  };
  const colorList = [
    { id: 1, color: "#005f73" },
    { id: 2, color: "#0a9396" },
    { id: 3, color: "#94d2bd" },
    { id: 4, color: "#ee9b00" },
    { id: 5, color: "#bb3e03" },
    { id: 6, color: "#0077b6" },
  ];

  const [isLargerThan768] = useMediaQuery("(min-width: 768px)");
  const [colorScheme, setColorScheme] = useState("#005f73");
  const changeHandler = (e: string) => {
    setColorScheme(e);
  };
  const howDo = [
    {
      id: 1,
      title: "Securite",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus assumenda eius iusto, vel aspernatur vero soluta. Iste quasi autem iusto ad architecto est dignissimos? Fugit doloribus itaque quis ipsum dolore.",
      imageLink: "./lieu_de_travail_fille.svg",
    },
    {
      id: 2,
      title: "Securite",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus assumenda eius iusto, vel aspernatur vero soluta. Iste quasi autem iusto ad architecto est dignissimos? Fugit doloribus itaque quis ipsum dolore.",
      imageLink: "./lieu_de_travail_fille.svg",
    },
    {
      id: 3,
      title: "Securite",
      description:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus assumenda eius iusto, vel aspernatur vero soluta. Iste quasi autem iusto ad architecto est dignissimos? Fugit doloribus itaque quis ipsum dolore.",
      imageLink: "./lieu_de_travail_fille.svg",
    },
  ];
  return (
    <>
      <Head>
        <title>RMY</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box w={"100%"}>
        {/* le <header></header> */}
        <Center
          w={"100%"}
          h={"7vh"}
          bg={colorPallete.primary_blue}
          position={"fixed"}
          zIndex={"banner"}
        >
          <Flex
            w={"90%"}
            h={"100%"}
            color={colorPallete.secondary_blue}
            justifyContent={"space-between"}
            alignItems={"center"}
          >
            <Heading>RMY</Heading>
            <Text>Connexion</Text>
          </Flex>
        </Center>

        <Center w={"100%"} h={"100vh"} bg={colorPallete.primary_blue}>
          <Flex w={"90%"} h={"90%"} bg={colorPallete.white}>
            <Flex
              w={{ base: "100%", sm: "50%" }}
              h={"100%"}
              bg={colorPallete.primary_blue}
              align={"start"}
              justifyContent={"center"}
              flexDirection={"column"}
            >
              <Heading color={colorPallete.white}>
                Gestion et suivi des<br></br>
                obligations avec<br></br>
              </Heading>
              <Heading color={colorPallete.secondary_blue}>RMY</Heading>
              <Text color={colorPallete.white}>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                <br></br>
                Tempore enim eaque veniam aliquam porro quae ut aperiam<br></br>
                fugit ab commodi est voluptatem nesciunt illo quam iure
                mollitia,
              </Text>
              <Button
                colorScheme="blue"
                w={"15em"}
                borderRadius={"full"}
                mt={"5"}
              >
                Button
              </Button>
            </Flex>
            {isLargerThan768 ? (
              <Center w={"50%"} h={"100%"} bg={colorPallete.white}>
                <Text>image</Text>
              </Center>
            ) : null}
          </Flex>
        </Center>

        {/* choisir son style  */}
        <Center
          w={"100%"}
          h={{ base: "auto", md: "100vh" }}
          flexDirection={"column"}
          mt={"4em"}
        >
          <Heading color={colorPallete.secondary_blue} textAlign={"center"}>
            {"Definissez votre propre style pour l'affichage"}
          </Heading>
          <Text mt={"5"} textAlign={"center"}>
            {"En un clic deffinissez l'affichage"}{" "}
          </Text>

          <Center w={"100%"} mt={"4em"}>
            <Flex
              w={{ base: "100%", md: "80%" }}
              h={{ base: "auto", md: "50vh" }}
              flexDirection={{ base: "column-reverse", md: "row" }}
            >
              <Center
                w={{ base: "100%", md: "80%" }}
                h={{ base: "50vh", md: "100%" }}
                bg={colorScheme}
              >
                Image
              </Center>

              <Center
                w={{ base: "100%", md: "20%" }}
                h={{ base: "10em", md: "100%" }}
              >
                <RadioGroup value={colorScheme} onChange={changeHandler}>
                  <Stack
                    direction={{ base: "row", md: "column" }}
                    justifyContent={"space-between"}
                  >
                    {colorList.map((color) => (
                      <Radio
                        key={color.id}
                        value={color.color}
                        bg={color.color}
                        colorScheme="blue"
                      ></Radio>
                    ))}
                  </Stack>
                </RadioGroup>
              </Center>
            </Flex>
          </Center>
        </Center>

        {/* comment ça marhce  */}
        <Center
          w={"100%"}
          h={{ base: "auto", md: "100vh" }}
          flexDirection={"column"}
        >
          <Heading color={colorPallete.secondary_blue}>
            {"Comment ça marche ?"}
          </Heading>
          <Center w={"100%"} h={{ base: "auto", md: "70vh" }} mt={"2em"}>
            <Flex
              w={"90%"}
              h={{ base: "auto", md: "90%" }}
              flexDirection={{ base: "column", md: "row" }}
              justifyContent={"space-between"}
              role="group"
              transition={"1s ease-in-out"}
            >
              {howDo.map((item) => (
                <HowDoCard key={item.id} howDo={item} />
              ))}
            </Flex>
          </Center>
        </Center>

        {/* nos avantages  */}
        <Center
          w={"100%"}
          h={{ base: "auto", md: "100vh" }}
          flexDirection={"column"}
          bg={colorPallete.black}
          color={colorPallete.white}
        >
          <Heading>Quelques avantages de notre solution</Heading>
          <Text
            textAlign={"center"}
            w={{ base: "100%", md: "40%" }}
            color={"#778da9"}
          >
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci
            sint nesciunt, vitae dicta quasi non, iure tempore vel deserunt
            eaque quod ullam ipsum accusantium porro suscipit omnis id
            praesentium facere?
          </Text>
        </Center>
      </Box>
    </>
  );
}
